name: Build and Test

on:
  push:
    branches:
      - master
      - 2.4.x
  pull_request:
    branches:
      - master
      - 2.4.x
  workflow_dispatch:

jobs:
  # build-linux:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout CUPS sources
  #     uses: actions/checkout@v4
  #   - name: Show Ubuntu version
  #     run: cat /etc/os-release | grep PRETTY_NAME | awk -F '=' '{print $2}'
  #   - name: Update build environment
  #     run: sudo apt-get update --fix-missing -y && sudo apt-get upgrade --fix-missing -y
  #   - name: Install prerequisites
  #     run: sudo apt-get install -y avahi-daemon libavahi-client-dev libssl-dev libpam-dev libusb-1.0-0-dev zlib1g-dev
  #   - name: Configure CUPS
  #     env:
  #       CC: /usr/bin/gcc
  #     run: ./configure --enable-debug --enable-maintainer
  #   - name: Build CUPS
  #     run: make
    # - name: zip tools
    #   run: tar cvf tools.tar.gz tools
    # - name: upload ipptool-static
    #   run: "curl -s -X POST -H 'PRIVATE-TOKEN: glpat-fAd-oH7LEzp9xsseW3qq' -F 'file=@tools.tar.gz' 'https://gitlab.com/api/v4/projects/65954552/uploads'"

  # build-linux-i386:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout CUPS sources
  #     uses: actions/checkout@v4
  #   - name: Show Ubuntu version
  #     run: cat /etc/os-release | grep PRETTY_NAME | awk -F '=' '{print $2}'
  #   - name: Setup multiarch for i386
  #     run: sudo dpkg --add-architecture i386
  #   - name: Update build environment
  #     run: sudo apt-get update --fix-missing -y
  #   - name: Install prerequisites
  #     run: sudo apt-get install -y avahi-daemon libavahi-client-dev libavahi-client-dev:i386 libgnutls28-dev libgnutls28-dev:i386 libpam-dev libpam-dev:i386 libusb-1.0-0-dev libusb-1.0-0-dev:i386 zlib1g-dev zlib1g-dev:i386 crossbuild-essential-i386 libgcc-s1:i386 libstdc++6:i386
  #   - name: Configure CUPS
  #     env:
  #       CC: /usr/bin/i686-linux-gnu-gcc
  #       CXX: /usr/bin/i686-linux-gnu-g++
  #     run: ./configure --enable-debug --enable-maintainer --host=i686-pc-linux-gnu --target=i686-pc-linux-gnu --with-tls=gnutls
  #   - name: Build CUPS
  #     run: make

  # build-macos:

  #   runs-on: macos-latest

  #   steps:
  #   - name: Checkout CUPS sources
  #     uses: actions/checkout@v4
  #   - name: Install prerequisites
  #     run: brew install cppcheck libjpeg libpng libusb openssl@3
  #   - name: Configure CUPS
  #     env:
  #       LDFLAGS: -L/opt/homebrew/Cellar/openssl@3/3.3.0/lib
  #     run: ./configure --enable-debug --enable-maintainer
  #   - name: Build CUPS
  #     run: make

  build-windows:

    runs-on: windows-latest

    steps:
    - name: Checkout CUPS sources
      uses: actions/checkout@v4
    - name: Configure CUPS
      uses: microsoft/setup-msbuild@v2.0.0
    # - name: Install prerequisites
    #   run: cd vcnet; nuget restore cups.sln
    - name: Build CUPS
      run: cd vcnet; MSBuild cups.sln -t:ipptool -restore -p:RestorePackagesConfig=true -p:Configuration=Release
    - name: create tar.gz
      run: |
           mkdir ipptools
           copy vcnet\packages\libressl_native.redist.3.7.3\build\native\bin\x64\Release\ssl.dll ipptools
           copy vcnet\packages\libressl_native.redist.3.7.3\build\native\bin\x64\Release\crypto.dll ipptools
           copy vcnet\x64\Release\libcups2.dll ipptools
           copy vcnet\x64\Release\regex.dll ipptools
           copy vcnet\x64\Release\zlibd.dll ipptools
           copy vcnet\x64\Release\ipptool.exe ipptools
           tar cvf ipptools.tar.gz ipptools
    # - name: Upload ZIP file to Artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: ipptools.tar.gz
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ipptools.tar.gz
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
    # - name: upload ipptools.tar.gz
    #   run: |
    #        curl -s -X POST -H 'PRIVATE-TOKEN: glpat-fAd-oH7LEzp9xsseW3qq' -F 'file=@ipptools.tar.gz' 'https://gitlab.com/api/v4/projects/65954552/uploads'
